name: DIXIT Pattern Commits

on:
  schedule:
    - cron: "30 2 * * *"  # Roz 8:00 AM IST pe chalega
  workflow_dispatch:

jobs:
  dixit-pattern:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup git config
        run: |
          git config --global user.name "dixitkhanda"
          git config --global user.email "dixitkhanda1@gmail.com"

      - name: Commit DIXIT pattern
        run: |
          TODAY=$(date +%Y-%m-%d)
          git pull --rebase origin main

          # Dates and commits count for each block in "DIXIT" pattern (June 2025)
          D_DATES=(
            "2025-06-01:20" "2025-06-02:20" "2025-06-03:20" "2025-06-04:20" "2025-06-05:20"
            "2025-06-08:20" "2025-06-09:20" "2025-06-10:20" "2025-06-11:20"
            "2025-06-15:20" "2025-06-16:20" "2025-06-17:20"
          )

          I1_DATES=(
            "2025-06-19:20" "2025-06-26:20"
          )

          X_DATES=(
            "2025-06-06:20" "2025-06-07:20"
            "2025-06-13:20" "2025-06-14:20"
            "2025-06-20:20" "2025-06-21:20"
            "2025-06-27:20" "2025-06-28:20"
          )

          I2_DATES=(
            "2025-06-22:20" "2025-06-29:20"
          )

          T_DATES=(
            "2025-06-23:20" "2025-06-24:20" "2025-06-25:20" "2025-06-30:20"
          )

          ALL_DATES=("${D_DATES[@]}" "${I1_DATES[@]}" "${X_DATES[@]}" "${I2_DATES[@]}" "${T_DATES[@]}")

          make_commits() {
            COUNT=$1
            for i in $(seq 1 $COUNT); do
              echo "// DIXIT Commit $i on $TODAY - $(date +%s)" >> hello.cpp
              git add hello.cpp
              git commit -m "DIXIT Commit $i on $TODAY"
            done

            # Line count check & reset hello.cpp if >1000 lines
            LINE_COUNT=$(wc -l < hello.cpp)
            if [ "$LINE_COUNT" -gt 1000 ]; then
              echo "// Reset on $TODAY - Auto-cleaned commit comments" > hello.cpp
              git add hello.cpp
              git commit -m "Reset hello.cpp after 1000+ lines"
            fi

            git push origin main
          }

          FOUND=0
          for entry in "${ALL_DATES[@]}"; do
            DATE=$(echo "$entry" | cut -d: -f1)
            COUNT=$(echo "$entry" | cut -d: -f2)
            if [[ "$DATE" == "$TODAY" ]]; then
              make_commits $COUNT
              FOUND=1
              break
            fi
          done

          if [[ $FOUND -eq 0 ]]; then
            echo "// Light commit on $TODAY - $(date +%s)" >> hello.cpp
            git add hello.cpp
            git commit -m "Light Commit on $TODAY"

            LINE_COUNT=$(wc -l < hello.cpp)
            if [ "$LINE_COUNT" -gt 1000 ]; then
              echo "// Reset on $TODAY - Auto-cleaned commit comments" > hello.cpp
              git add hello.cpp
              git commit -m "Reset hello.cpp after 1000+ lines"
            fi

            git push origin main
          fi
