name: DIXIT Pattern Commits

on:
  schedule:
    - cron: "30 2 * * *"  # Roz 8:00 AM IST pe chalega
  workflow_dispatch:

jobs:
  dixit-pattern:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup git config
        run: |
          git config --global user.name "dixitkhanda"
          git config --global user.email "dixitkhanda1@gmail.com"

      - name: Commit DIXIT pattern
        run: |
          TODAY=$(date +%Y-%m-%d)
          git pull --rebase origin main

          # Dates and commits count for each block in "DIXIT" pattern (June 2025)
          # Format: YYYY-MM-DD:commit_count
          # 20 commits = dark green, less commits = lighter color

          D_DATES=(
            "2025-06-01:20" "2025-06-02:20" "2025-06-03:20" "2025-06-04:20" "2025-06-05:20"
            "2025-06-08:20" "2025-06-09:20" "2025-06-10:20" "2025-06-11:20"
            "2025-06-15:20" "2025-06-16:20" "2025-06-17:20"
          )

          I1_DATES=(
            "2025-06-19:20" "2025-06-26:20"
          )

          X_DATES=(
            "2025-06-06:20" "2025-06-07:20"
            "2025-06-13:20" "2025-06-14:20"
            "2025-06-20:20" "2025-06-21:20"
            "2025-06-27:20" "2025-06-28:20"
          )

          I2_DATES=(
            "2025-06-22:20" "2025-06-29:20"
          )

          T_DATES=(
            "2025-06-23:20" "2025-06-24:20" "2025-06-25:20" "2025-06-30:20"
          )

          ALL_DATES=("${D_DATES[@]}" "${I1_DATES[@]}" "${X_DATES[@]}" "${I2_DATES[@]}" "${T_DATES[@]}")

          make_commits() {
            COUNT=$1
            for i in $(seq 1 $COUNT); do
              echo "// DIXIT Commit $i on $TODAY" >> hello.cpp
              git add hello.cpp
              git commit -m "DIXIT Commit $i on $TODAY"
            done
            git push origin main
          }

          FOUND=0
          for entry in "${ALL_DATES[@]}"; do
            DATE=$(echo "$entry" | cut -d: -f1)
            COUNT=$(echo "$entry" | cut -d: -f2)
            if [[ "$DATE" == "$TODAY" ]]; then
              make_commits $COUNT
              FOUND=1
              break
            fi
          done

          if [[ $FOUND -eq 0 ]]; then
            # Agar aaj pattern me date nahi hai to halki green ke liye ek commit
            echo "// Light commit on $TODAY" >> hello.cpp
            git add hello.cpp
            git commit -m "Light Commit on $TODAY"
            git push origin main
          fi
